Repository fave77/pbchess, pull requests merged in 2021-04, with the labels that each got.

#86 Reset Password
  client/src/App.js
  client/src/components/login/login.css
  client/src/components/login/login.js
  client/src/components/navbar/navbar.js
  client/src/components/password/password.css
  client/src/components/password/password.js
  client/src/components/password/reset-password.js
  client/src/components/password/update-password.js
  client/src/services/auth.service.js
  client/src/services/validation.service.js
  server/src/controllers/user.controller.js
  server/src/routes/user.route.js
  server/src/services/auth.service.js
  server/src/services/email.service.js
  server/src/services/password.service.js
Labels: Level2, gssoc21

#89 Fixed the oauth username bug
  server/src/controllers/user.controller.js
Labels: Level1, gssoc21

#90 fix(learn): added tabs and player size fix
  client/src/components/learn/learn.css
  client/src/components/learn/learn.js
  client/src/components/videos/videos.css
  client/src/components/videos/videos.js
Labels: Level2, gssoc21

#95 Removed statements exposing the tokens on client.
  client/src/App.js
  client/src/components/game/game.js
  client/src/components/lobby/join-game.js
  client/src/components/lobby/lobby.js
  client/src/components/login/login.js
  client/src/components/navbar/navbar.js
  client/src/components/password/update-password.js
  client/src/components/timer/timer.js
  client/src/components/vocab/vocab.js
Labels: Level0, gssoc21

#101 alignment_fixed
  client/src/components/vocab/vocab.css
Labels: Level0, gssoc21

#105 Reset Password problem rectified
  client/src/components/password/reset-password.js
Labels: Level1, gssoc21

#108 Tooltip Modified
  client/src/components/navbar/navbar.css
  client/src/components/navbar/navbar.js
Labels: Level0, gssoc21

#120 Created chess_openings.md file
  .github/Lessons/chess_openings.md
Labels: Level1, gssoc21

#123 fixed-scroll-branch-conflict
  client/src/App.css
Labels: Level1, gssoc21

#124 scroll-to-top of contribute page
  client/src/components/contrib/contrib.css
  client/src/components/contrib/contrib.js
Labels: Level1, gssoc21

#128 Collapsing nav_fixed
  client/package-lock.json
  client/package.json
  client/src/components/navbar/navbar.js
Labels: Level2, gssoc21

#125 feat: Addition of Icons and Navbar Alignment
  client/src/components/navbar/navbar.css
  client/src/components/navbar/navbar.js
Labels: Level1, gssoc21

#132 Added placeholders to login.js and register.js
  client/src/components/login/login.js
  client/src/components/register/register.js
Labels: Level1, gssoc21

#131 hover on navbar-links
  client/src/components/navbar/navbar.css
  client/src/components/navbar/navbar.js
Labels: Level1, gssoc21

#133 Contributers Card
  client/src/components/contrib/contrib.css
Labels: Level2, gssoc21
