Repository fave77/pbchess, pull requests merged in 2021-03, with the labels that each got.

#32 grokking_chess.md file added
  .github/Lessons/grokking_chess.md
Labels: gssoc21

#37 Implemented turn toggle
  client/src/components/game/game.js
  client/src/components/lobby/lobby.js
  client/src/components/user/user.css
  client/src/components/user/user.js
Labels: Level3, gssoc21

#43 Implemented Join/create instead
  client/src/components/lobby/lobby.css
  client/src/components/lobby/lobby.js
Labels: Level2, gssoc21

#44 Provide an article on chess - Chess Vocab: Speaking the common tongue ( issue #29 )
  client/src/components/learn/learn.css
  client/src/components/learn/learn.js
  client/src/components/vocab/Terms.json
  client/src/components/vocab/vocab.css
  client/src/components/vocab/vocab.js
Labels: Level2, gssoc21

#48 Improved Landing page UI
  client/src/components/home/home.css
Labels: Level0, gssoc21

#53 Added a way to send emails when the user registers without using google
  client/src/components/login/login.js
  server/src/controllers/user.controller.js
Labels: Level2, gssoc21

#55 Fixed #52: Learn page scaling properly
  client/src/components/vocab/Terms.json
  client/src/components/vocab/vocab.css
  client/src/components/vocab/vocab.js
Labels: Level2, gssoc21

#59 Added email validation on the server side and client side.
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/confirm/confirm.css
  client/src/components/confirm/confirm.js
  client/src/components/register/register.js
  client/src/services/auth.service.js
  server/src/controllers/user.controller.js
  server/src/models/user.model.js
  server/src/routes/user.route.js
  server/src/services/email.service.js
Labels: Level3, gssoc21

#62 Fixed the bug where mutiple users can register using the same email
  server/src/controllers/user.controller.js
Labels: Level0, gssoc21

#70 Added update password feature and made the password more secure
  client/src/App.js
  client/src/components/navbar/navbar.js
  client/src/components/password/password.css
  client/src/components/password/password.js
  client/src/components/register/register.js
  client/src/services/auth.service.js
  server/src/controllers/user.controller.js
  server/src/routes/user.route.js
Labels: Level3, gssoc21

#72 contributor's page 🔨
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/contrib/contrib-card.js
  client/src/components/contrib/contrib.css
  client/src/components/contrib/contrib.js
  client/src/components/contrib/profile-card.js
  client/src/components/footer/footer.js
Labels: Level3, gssoc21

#79 Timeout feature
  client/package-lock.json
  client/package.json
  client/src/components/game/game.js
  client/src/components/lobby/lobby.js
  client/src/components/timer/timer.css
  client/src/components/timer/timer.js
  client/src/components/user/user.js
  client/src/test/App.test.js
  server/src/controllers/game.controller.js
  server/src/routes/socket.route.js
  server/src/services/chess.service.js
Labels: Level3, gssoc21

#82 bug(vocab): removed alphabets without terms
  client/src/components/vocab/vocab.js
Labels: Level1, gssoc21

#80 Lichess login
  .github/CONTRIBUTING/CONTRIBUTING.md
  client/src/components/footer/footer.js
  client/src/components/login/login.css
  client/src/components/login/login.js
  client/src/images/lichesslogo.svg
  server/package-lock.json
  server/package.json
  server/src/configs/auth.config.js
  server/src/controllers/user.controller.js
  server/src/models/profile.model.js
  server/src/routes/user.route.js
Labels: Level3, gssoc21
